services:
  - type: web
    name: plant-diagnosis-api
    env: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: PORT
        value: $PORT
